development:
  adapter: postgresql
  encoding: unicode
  database: my_database_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: my_database_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  username:
  password:
